# Generated by Django 5.2 on 2025-05-01 15:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_alter_jobseeker_job'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobseeker',
            name='job',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.employer'),
        ),
    ]
